/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Player = IDL.Record({
  'score' : IDL.Nat,
  'isAlive' : IDL.Bool,
  'health' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getOrCreatePlayer' : IDL.Func([], [], []),
  'getScore' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'revive' : IDL.Func([], [], []),
  'shoot' : IDL.Func([IDL.Principal], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Player = IDL.Record({
    'score' : IDL.Nat,
    'isAlive' : IDL.Bool,
    'health' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getOrCreatePlayer' : IDL.Func([], [], []),
    'getScore' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'revive' : IDL.Func([], [], []),
    'shoot' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };